<marquee> SELAMAT DATANG DI WEBSITE PENDATAAN BARANG PANGLONG LANCAR JAYA</marquee>
<h2>HOME</h2>
<div class="info">WEBSITE INI ADALAH WEBSITE PENDATAAN BARANG SALAH SATU USAHA DAGANG PANGLONG
LANCAR JAYA YANG ADA DI TEMBUNG</div>